[package]
name = "quizface"
version = "0.1.0"
authors = ["ha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
